# Site settings
title: "e-guy"
email: e-guy@foxmail.com
description: "A dark blog theme for Robin."
baseurl: ""
url: "https://e-guy.github.io/about"
title_description: "Artificial Intelligence    Machine Learning    Deep Learning    Computer Vision    Natural Lauguage Processing    Robotic Software Architecture    Data Mining   Big Data"
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/e-guy
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
instagram_username: 
reddit_username: 
linkedin_link: https://e-guy.github.io/
google_plus_link: https://e-guy.github.io/
stackoverflow_link: https://e-guy.github.io/
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
